+++ Running indexing on /var/tmp/pbench-test-server/test-7.3
Other error 'end_run'
Traceback (most recent call last):
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 293, in mk_run_metadata
    d['end_run'] = d['end_run'].replace('_', 'T')
KeyError: 'end_run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 899, in main
    actions, toc_extra = mk_actions(hostname, tbname, dirname, dirprefix, tb, mdconf, idxname, options)
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 748, in mk_actions
    actions.append(mk_results_action(hostname, tbname, dirname, dirprefix, tb, mdconf, idxname, md5sum, ts, options))
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 695, in mk_results_action
    source = mk_source(hostname, tbname, dirname, dirprefix, tb, mdconf, md5sum, options)
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 633, in mk_source
    rec['run'] = mk_run_metadata(mdconf,dirname, dirprefix)
  File "/home/user/repo/pbench/server/pbench/bin/index-pbench", line 304, in mk_run_metadata
    raise Exception(e)
Exception: 'end_run'

--- Finished indexing on /var/tmp/pbench-test-server/test-7.3 (status=11)
+++ pbench tree state
/var/tmp/pbench-test-server/pbench
--- pbench tree state
+++ pbench log file contents
--- pbench log file contents
